export enum AuthActionType {
  SIGN_IN = 'SB/AUTH/SIGN_IN',
  LOG_OUT = 'SB/AUTH/LOG_OUT',
  AUTH_ME = 'SB/AUTH/AUTH_ME',
  AUTH_NOT_VALID = 'SB/AUTH/NOT_VALID',
  GET_CAPTCHA_URL_SUCCESS = 'SB/AUTH/GET_CAPTCHA_URL',
}
