export enum AuthActionType {
  SIGN_IN = 'SB/AUTH/SIGN_IN',

  LOG_OUT_START = 'SB/AUTH/LOG_OUT_START',
  LOG_OUT_ACCEPTED = 'SB/AUTH/LOG_OUT_ACCEPTED',
  LOG_OUT_DENIED = 'SB/AUTH/LOG_OUT_DENIED',

  AUTH_ME = 'SB/AUTH/AUTH_ME',
  AUTH_NOT_VALID = 'SB/AUTH/NOT_VALID',
  GET_CAPTCHA_URL_SUCCESS = 'SB/AUTH/GET_CAPTCHA_URL',
}
