enum ProfileActionType {
  SET_USER_PROFILE = 'SB/PROFILE/SET_USER_PROFILE',
  SET_OWNER_PROFILE = 'SB/PROFILE/SET_OWNER_PROFILE',
  SET_OWNER_STATUS = 'SB/PROFILE/SET_OWNER_STATUS',
  GET_PROFILE_STATUS = 'SB/PROFILE/GET_PROFILE_STATUS',
  SET_PROFILE_STATUS = 'SB/PROFILE/SET_PROFILE_STATUS',
  GET_FOLLOWING_STATUS = 'SB/PROFILE/GET_FOLLOWING_STATUS',
  NEW_PROFILE_PHOTO_SENDS = 'SB/PROFILE/NEW_PHOTO_SENDS',
  SAVE_PHOTO_SUCCESS = 'SB/PROFILE/SAVE_PHOTO_SUCCESS',
  SAVE_PROFILE_SUCCESS = 'SB/PROFILE/SAVE_PROFILE_SUCCESS',
  SAVE_PROFILE_FAILED = 'SB/PROFILE/SAVE_PROFILE_FAILED',
  SHOW_PROFILE_LOADER = 'SB/PROFILE/SHOW_PROFILE_LOADER',
  ADD_POST = 'SB/POSTS/CREATE_POST',
  REMOVE_POST = 'SB/POSTS/REMOVE_POST',
}

export default ProfileActionType