export enum UsersActionType {
  SET_USERS = 'SB/USERS/SET_USERS',
  SET_USERS_SUCCESS = 'SB/USERS/SET_USERS_SUCCESS',
  SET_FRIENDS_SUCCESS = 'SB/USERS/SET_FRIENDS_SUCCESS',
  SET_TOTAL_USERS_COUNT = 'SB/USERS/SET_TOTAL_COUNT',
  SET_CURRENT_PAGE = 'SB/USERS/SET_CURRENT_PAGE',
  TOGGLE_FOLLOW_UNFOLLOW = 'SB/USERS/TOGGLE_FOLLOW_UNFOLLOW',
  TOGGLE_IS_FOLLOWING_PROGRESS = 'SB/USERS/TOGGLE_IS_FOLLOWING_PROGRESS',
  SET_USERS_FILTER = 'SB/USERS/SET_USERS_FILTER',
  TOGGLE_IS_FETCHING_USERS = 'SB/USERS/TOGGLE_IS_FETCHING',
}
