/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e1c649f0-00df-42a0-8178-0cc1a9023787",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_D5Qm43nto",
    "aws_user_pools_web_client_id": "1h3uf838p2s65rd4shgau58114",
    "oauth": {}
};


export default awsmobile;
